AWSTemplateFormatVersion: '2010-09-09'
Metadata:
  Name: alexa-skills-kit-nodejs-factskill
Transform: AWS::Serverless-2016-10-31
Resources:
  alexaskillskitnodejsfactskill:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      Description: Demonstrate a basic fact skill built with the ASK NodeJS SDK
      Timeout: 7
      CodeUri:
        Bucket: awsserverlessrepo-changesets-18ssd5swmy82n
        Key: 501237108406-947732d3-cec1-4e80-9596-37206a195f9d
      Runtime: nodejs8.10
      MemorySize: 128
      Events:
        AlexaTrigger:
          Type: AlexaSkill
Description: Demonstrate a basic fact skill built with the ASK NodeJS SDK